#!/usr/bin/env bash
# FindingTheSquad - Quick Commands Reference
# Run these commands to get the application running

echo "🎮 FindingTheSquad - Quick Start"
echo "=================================="
echo ""
echo "Choose an option:"
echo ""
echo "1. Start Backend"
echo "   cd src/backend/FindingTheSquad.WebApi"
echo "   dotnet run"
echo ""
echo "2. Start Frontend" 
echo "   cd src/frontend"
echo "   npm run dev"
echo ""
echo "3. Build Frontend for Production"
echo "   cd src/frontend"
echo "   npm run build"
echo ""
echo "4. Preview Production Build"
echo "   cd src/frontend"
echo "   npm run preview"
echo ""
echo "5. View Documentation"
echo "   • 00_START_HERE.txt (Quick Reference)"
echo "   • SETUP_GUIDE.md (Getting Started)"
echo "   • VISUAL_GUIDE.md (Architecture)"
echo "   • CHECKLIST.md (Testing)"
echo "   • IMPLEMENTATION_SUMMARY.md (Technical)"
echo ""
echo "Frontend will be at: http://localhost:5173"
echo "Backend will be at: http://localhost:5121"
echo ""
echo "=================================="
echo "✅ All systems ready!"
echo "=================================="

